In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size = 100000

In [7]:
# One Hot Representation

one_hot_repr = [one_hot(word, voc_size) for word in sent]
one_hot_repr



[[8310, 66459, 38152, 16661],
 [8310, 66459, 38152, 82490],
 [8310, 62026, 38152, 4914],
 [84431, 40976, 40760, 1594, 63505],
 [84431, 40976, 40760, 1594, 43673],
 [82339, 8310, 5221, 38152, 46676],
 [85869, 37489, 91034, 1594]]

In [12]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [14]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[    0,     0,     0,     0,  8310, 66459, 38152, 16661],
       [    0,     0,     0,     0,  8310, 66459, 38152, 82490],
       [    0,     0,     0,     0,  8310, 62026, 38152,  4914],
       [    0,     0,     0, 84431, 40976, 40760,  1594, 63505],
       [    0,     0,     0, 84431, 40976, 40760,  1594, 43673],
       [    0,     0,     0, 82339,  8310,  5221, 38152, 46676],
       [    0,     0,     0,     0, 85869, 37489, 91034,  1594]])

In [15]:
## Feature Exraction

dim=10

In [16]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             1000000   
                                                                 
Total params: 1000000 (3.81 MB)
Trainable params: 1000000 (3.81 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 310ms/step


array([[[ 0.02745477,  0.03850808, -0.00771869, -0.04735311,
         -0.02055248,  0.03993739, -0.03105893, -0.0127233 ,
         -0.00506378,  0.03109558],
        [ 0.02745477,  0.03850808, -0.00771869, -0.04735311,
         -0.02055248,  0.03993739, -0.03105893, -0.0127233 ,
         -0.00506378,  0.03109558],
        [ 0.02745477,  0.03850808, -0.00771869, -0.04735311,
         -0.02055248,  0.03993739, -0.03105893, -0.0127233 ,
         -0.00506378,  0.03109558],
        [ 0.02745477,  0.03850808, -0.00771869, -0.04735311,
         -0.02055248,  0.03993739, -0.03105893, -0.0127233 ,
         -0.00506378,  0.03109558],
        [-0.03278833, -0.02300494, -0.02865194,  0.00907148,
          0.04607547, -0.01499388,  0.01950089, -0.02906351,
          0.00338653,  0.02702148],
        [-0.03393288, -0.04706965,  0.0279108 , -0.01437209,
          0.01946378, -0.0395956 , -0.01449681,  0.03340054,
         -0.0050302 , -0.03943559],
        [-0.02182406, -0.03444018,  0.01741042,  0.0

In [ ]:
embedded_docs[0]

array([    0,     0,     0,     0,  8310, 66459, 38152, 16661])